###############################################################
# References
###############################################################
version: 2.1
references:
  restore-npm-cache: &restore-npm-cache
    restore_cache:
      keys:
        # when lock file changes, use increasingly general patterns to restore cache
        - npm-packages-v1-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
        - npm-packages-v1-{{ checksum "package.json" }}
        - npm-packages-v1-

  save-npm-cache: &save-npm-cache
    save_cache:
      paths:
        - node_modules/
      key: npm-packages-v1-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

###############################################################
# Workflows
###############################################################
workflows:
  # Trigger workflow for last commit (merge commits) to master
  # Run unit tests for sanity and if all looks good run semantic release
  # Semantic release will decide based on commit messages if another release is needed
  # Always run unit tests on master
  automatic-semantic-release:
    jobs:
      - verify-unit-tests:
          filters:
            branches:
              only:
                - master
      - run-semantic-release:
          requires:
            - verify-unit-tests
          filters:
            branches:
              only:
                - master
            tags:
              # Would be good if we can ignore tagged commits but it won't trigger another build so it's fine
              ignore: /.*/

  # This gets triggers on every push to all branches except master
  # It verifies the branch, runs unit tests and coverage
  verify-test-build:
    jobs:
      - verify-unit-tests:
          filters:
            branches:
              ignore:
                - master

###############################################################
# Jobs
###############################################################

jobs:
  verify-unit-tests:
    working_directory: ~/project
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - *restore-npm-cache
      - run:
          name: Install node modules
          command: yarn install --frozen-lockfile
      - *save-npm-cache
      - run:
          name: Run unit tests
          command: yarn run test:ci
      - run:
          name: Run lint
          command: yarn run lint
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  run-semantic-release:
    working_directory: ~/project
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - run:
          name: Semantic release
          command: |
            git config user.email "devops@uport.me"
            git config user.name "uport-automation-bot"
            yarn run release
