name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  release:
    runs-on: ubuntu-26.04
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
      - name: 'Setup Node.js'
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24

      - run: pnpm install --frozen-lockfile
      - run: pnpm run format
      - run: pnpm run build
      - run: pnpm run lint
      - run: pnpm run test:ci

      - name: 'Create release PR or publish packages'
        id: changesets
        uses: changesets/action@ae32849d5ba541f9ae29e40e22a623bc13562f51 # v2.1.2
        with:
          pr-title: 'chore(release): version packages'
          commit-message: 'chore(release): version packages'
          github-token: ${{ github.token }}
          publish-script: 'pnpm run release:publish'

      - name: Upload coverage reports
        uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
